version: "3.8"

services:
  network-dashboard:
    build: .
    container_name: network-dashboard
    ports:
      - "5000:5000"
    restart: unless-stopped
    
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    
    # Permissões necessárias para o Nmap realizar scans avançados (-sS, -sU, -sV)
    # NET_RAW permite a manipulação de pacotes para o Stealth Scan
    cap_add:
      - NET_RAW
      - NET_ADMIN
